CREATE DATABASE Company;
USE Company;
SHOW DATABASES;
CREATE TABLE Department(department_id INT PRIMARY KEY, department_name VARCHAR(50), location VARCHAR(50));
INSERT INTO Department VALUES (1,'IT','Pune'), (2, 'HR', 'Mumbai'), (3, 'Finance', 'De;hi'), (4, 'Sales', 'Banglore'), (5, 'Marketing', 'Hydrabad'), (6, 'Customer Support', 'Kolkata'), (7, 'Quality Assurance', 'Pune'), (8,'Product Manager', 'Banglore'), (9, 'Cyber Securty', 'Chennai'),(10, 'Traning Department', 'Delhi'); 
CREATE TABLE Employee (Employee_id INT PRIMARY KEY, Employee_name VARCHAR(100), Salary DECIMAL(10,2), Hire_date DATE, Department_id INT); 
INSERT INTO Employee VALUES(101,'Rahul',50000,'2025-01-15',1), (102,'Priya',60000,'2025-02-20',1), (103,'Amit',70000,'2024-11-10',2), (104,'Sneha',80000,'2025-03-12',2), (105,'Rohit',90000,'2025-04-05',3), (106,'Anjali',55000,'2025-05-15',3), (107,'Vikas',65000,'2025-06-01',4), (108,'Neha',75000,'2025-06-10',4), (109,'Rahul',50000,'2025-01-15',1),(110,'Suhas',85000,'2025-01-25',1);
SHOW Tables;
SELECT * FROM Employee ORDER BY Salary DESC LIMIT 5;
SELECT Department_id, count(*) AS Employee_Count FROM Employee GROUP BY Department_id;
SELECT MAX(Salary) AS Second_Highest_Salary FROM Employee WHERE Salary <(SELECT MAX(Salary) FROM Employee);
SELECT e.* FROM Employee e WHERE e.Salary >(SELECT AVG(e2.Salary) FROM Employee e2 WHERE e2.Department_id = e.Department_id);
SELECT e.Employee_id, e.Employee_name, e.Salary, d.department_name FROM Employee e INNER JOIN Department d ON e.Department_id = d.department_id;
SELECT e.Employee_id, e.Employee_name, d.department_name FROM Employee e LEFT JOIN Department d ON e.Department_id = d.department_id;
SELECT Department_id, COUNT(*) AS Total_Employees FROM Employee GROUP BY Department_id HAVING COUNT(*) > 2;
SELECT * FROM Employee WHERE Hire_date >= DATE_SUB(CURDATE(), INTERVAL 6 MONTH);
SELECT Employee_name, COUNT(*) AS Duplicate_Count FROM Employee GROUP BY Employee_name, Salary, Hire_date, Department_id HAVING COUNT(*) > 1;
DELETE FROM Employee WHERE Employee_id = 109;
SELECT * FROM Employee;